"""Initiative setup generator — turns an InitiativeBrief into the full file set.

Writes:
  data/<slug>/teams/<team-slug>/team.yaml     (one per team)
  data/<slug>/journeys.yaml
  data/<slug>/experience_principles.yaml
  data/<slug>/org_objectives.yaml             (if north_star present)

All files are DRAFT — commented to make that clear — and immediately usable
by `syncbot validate`. No YAML knowledge required from the person setting up.
"""
from __future__ import annotations
import os
import re
import yaml
from datetime import date
from .extractor import InitiativeBrief


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:40]


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def generate(brief: InitiativeBrief, output_dir: str) -> list[str]:
    """Write all setup files. Returns list of paths written."""
    written: list[str] = []
    initiative_slug = _slug(brief.title or brief.client or "initiative")
    base = os.path.join(output_dir, initiative_slug)
    today = str(date.today())

    # ── team manifests ────────────────────────────────────────────────────────
    teams_dir = os.path.join(base, "teams")
    for i, team in enumerate(brief.teams, 1):
        slug = _slug(team.name) or f"team-{i}"
        members_yaml = ""
        for m in team.members:
            members_yaml += f"  - name: {m}\n    role: Team Member\n    slack_handle: \"\"\n    email: \"\"\n"
        if not members_yaml:
            members_yaml = "  []  # TODO: add team members\n"

        manifest = f"""\
# DRAFT — generated by SyncBot onboarding. Review and confirm all fields.
# Fields marked TODO need your input; 'inferred' fields came from the brief.
team: "{team.name}"
description: "{team.focus or 'TODO: one-line description of what this team works on'}"
owner:
  name: ""  # TODO: who leads this team?
  role: ""
  slack_handle: ""
  email: ""
members:
{members_yaml}
slack_channel: ""  # TODO: e.g. #payments-team
jira_project: ""   # TODO if using Jira (or leave blank)
confluence_space: "" # TODO if using Confluence (or leave blank)
figma_files: []   # TODO: add Figma file URLs for this team
design_system_library: ""
components:
  code: []   # TODO: what code components / areas does this team own?
  design: [] # TODO: what design components does this team own?
dependencies: []  # TODO: which other teams does this team depend on?
roadmap_link: ""
quarter_goals: []  # TODO: what are this team's goals this quarter?
resources: []
last_verified: {today}
"""
        path = os.path.join(teams_dir, slug, "team.yaml")
        _write(path, manifest)
        written.append(path)

    # ── journeys ─────────────────────────────────────────────────────────────
    journeys_data = {"journeys": []}
    for j in brief.journeys:
        entry = {
            "name": j.name,
            "description": j.description or f"TODO: describe the {j.name} journey",
            "stages": ["TODO: stage 1", "TODO: stage 2", "TODO: stage 3"],
            "teams": j.teams if j.teams else [t.name for t in brief.teams[:2]],
            "components": [],
            "owner": "TODO: experience DRI",
            "north_star": j.north_star or brief.north_star or "TODO: the outcome this journey is judged by",
        }
        journeys_data["journeys"].append(entry)

    if journeys_data["journeys"]:
        path = os.path.join(base, "journeys.yaml")
        header = (
            "# DRAFT journeys — generated from the initiative brief.\n"
            "# Each journey is an end-to-end experience spanning multiple teams.\n"
            "# Fill in stages, teams, components, and the experience owner.\n\n"
        )
        _write(path, header + yaml.dump(journeys_data, allow_unicode=True, sort_keys=False))
        written.append(path)

    # ── experience principles ─────────────────────────────────────────────────
    if brief.principles:
        principles_data = {"principles": []}
        for i, p in enumerate(brief.principles, 1):
            kws = p.keywords if p.keywords else [w.lower() for w in p.name.split() if len(w) > 3]
            entry = {
                "id": f"EP-{i}",
                "name": p.name,
                "statement": p.statement or f"TODO: write the full statement for '{p.name}'",
                "keywords": kws,
            }
            principles_data["principles"].append(entry)

        path = os.path.join(base, "experience_principles.yaml")
        header = (
            "# DRAFT experience principles — generated from the initiative brief.\n"
            "# These are the values all work is measured against.\n"
            "# Fill in the 'statement' for each (one sentence on what it means in practice).\n\n"
        )
        _write(path, header + yaml.dump(principles_data, allow_unicode=True, sort_keys=False))
        written.append(path)

    # ── org objectives (from north star + open decisions) ─────────────────────
    if brief.north_star or brief.open_decisions:
        objectives = {"objectives": []}
        if brief.north_star:
            objectives["objectives"].append({
                "id": "OBJ-1",
                "title": brief.north_star,
                "keywords": [w.lower() for w in brief.north_star.split() if len(w) > 4][:8],
            })
        path = os.path.join(base, "org_objectives.yaml")
        header = (
            "# DRAFT objectives — generated from the initiative brief.\n"
            "# Add keywords so team goals can be automatically matched against these.\n\n"
        )
        _write(path, header + yaml.dump(objectives, allow_unicode=True, sort_keys=False))
        written.append(path)

    # ── config snippet ────────────────────────────────────────────────────────
    config_snippet = f"""\
# Add this to config.yaml to point SyncBot at your initiative data:
# data:
#   teams_dir: ./data/{initiative_slug}/teams
# And place journeys.yaml / experience_principles.yaml / org_objectives.yaml
# in ./data/{initiative_slug}/
"""
    path = os.path.join(base, "HOW-TO-USE.txt")
    _write(path, config_snippet + f"\nFiles generated: {len(written)}\nDate: {today}\n")
    written.append(path)

    return written


def summary(brief: InitiativeBrief, written: list[str]) -> str:
    lines = [
        f"✅ *Initiative setup complete for '{brief.title or brief.client}'*\n",
        f"Generated {len(written)} files:\n",
    ]
    for path in written:
        lines.append(f"  • `{path}`")
    lines.append("")
    if brief.teams:
        lines.append(f"*Teams:* {', '.join(t.name for t in brief.teams)}")
    if brief.journeys:
        lines.append(f"*Journeys:* {', '.join(j.name for j in brief.journeys)}")
    if brief.principles:
        lines.append(f"*Principles:* {', '.join(p.name for p in brief.principles)}")
    if brief.open_decisions:
        lines.append(f"\n*⚠️ Open decisions to resolve ({len(brief.open_decisions)}):*")
        for d in brief.open_decisions[:5]:
            lines.append(f"  • {d}")
    lines.append("\n_Review the generated files — fields marked TODO need your input. Then `syncbot validate` to confirm everything's good._")
    return "\n".join(lines)
